apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Default project, should not be used

  sourceRepos: [] # no git repo allowed

  destinations: [] # cannot deploy anything with default project

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist: []

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist: []
