argo-cd:

  ## Dex
  dex:
    enabled: false

  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      labels: {}
      ingressClassName: nginx
      hosts:
        - clementde.playground.padok.cloud
      paths:
        - /
    ingressGrpc:
      enabled: false
